- hosts: localhost
  gather_facts: false
  tasks:
  - name: Make sure portgroup exists on each host (esxi)
    community.vmware.vmware_portgroup:
      hostname: '{{ item }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'

      esxi_hostname: "{{ item }}"

      switch: "{{ switch_name }}"
      portgroup: "{{ portgroup_name }}"
      vlan_id: '{{ vlan_id }}'

      #security:
      #    promiscuous_mode: false
      #    mac_changes: false
      #    forged_transmits: false
      traffic_shaping:
          enabled: false

      state:    '{{ state }}'
    delegate_to: localhost
    loop: '{{ esxi_hostnames }}'