- hosts: localhost
  gather_facts: false
  tasks:
  - name: Add a VMware vSwitch formacion
    community.vmware.vmware_vswitch:
      hostname: '{{ item }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      switch:   '{{ switch_name }}'
      mtu:      9000
      state:    '{{ state }}'
    delegate_to: localhost
    loop: '{{ esxi_hostnames }}'